### ISSUE TITLE
Remove the ability to delete individual log entries

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe.Logging#31]
I’m wondering why the system log has functionality to delete individual entries. This makes the layout a little more awkward than it would be otherwise, also affecting ease of copying and pasting log entries.  Does anyone think this is needed? If anything, to me it seems wrong that you should be able to delete individual log entries, as that could make the entire sequence confusing. We do anyway have the ability to delete the whole log or entries "older than n days".

**Comment by JimKerslake** [comment]
@CrispinF Your commit there looked as though it was just commenting out the Delete form, so presumably if any CS users out there really want this functionality they could just override the view to bring it back (since I didn't see you removing any of the back-end support for it).  Alternatively, if the world really wants it, it could perhaps be added to the logger configuration setup as a boolean preference..?

**Comment by CrispinF** [comment]
That's right. I'm happy we should remove it, and if anyone wants it back enough we could add it back through config (or they could override the view as you say).
